const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const report={checks:[],errors:[],viewports:[]};
const ok=(name,value)=>{assert(value,name);report.checks.push(name);};
(async()=>{
 const local='/ms-playwright/chromium_headless_shell-1208/chrome-headless-shell-linux64/chrome-headless-shell';
 const executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||(fs.existsSync(local)?local:undefined);
 const browser=await chromium.launch({executablePath,args:['--no-sandbox']});
 try{
  const p=await browser.newPage({viewport:{width:390,height:844},acceptDownloads:true});
  p.setDefaultTimeout(8000);p.on('pageerror',e=>report.errors.push(e.stack));
  let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
  html=html.replace("loadFont();renderAll();pushHist();","window.__test={S,P,UI,ctx,commit,renderPaper,parsePieces,piecesToTex,richHTML,texToHTML,texProblem,serClean,equationProblem,kindTemplate,makeProject,normProject,matchOrder,setPath};loadFont();renderAll();pushHist();");
  await p.route('**/*',r=>r.request().url().startsWith('file:')?r.fulfill({contentType:'text/html',body:html}):r.abort());
  await p.goto('file://'+path.join(root,'index.html'),{waitUntil:'commit'});
  await p.locator('[data-act=homeNew]').click();
  await p.locator('#wizard [data-act=wzNext]').click();
  await p.locator('#wizard [data-act=wzNext]').click();
  await p.locator('#wizard [data-act=wzNext]').click();
  ok('first-run wizard creates an exam',!await p.locator('#wizard').isVisible());
  await p.evaluate(()=>{for(const k of Object.keys(__test.S.stages))__test.S.stages[k]=__test.makeProject(k,false);__test.UI.view='questions';__test.UI.adding=false;__test.commit();});
  await p.locator('details.menu summary').click();
  ok('menu is not clipped by header',await p.locator('.menu-m [data-act=save]').isVisible());
  await p.locator('details.menu summary').click();
  await p.locator('[data-act=adding]').click();
  await p.locator('[data-act=addQ][data-kind=mcq]').click();
  const qid=await p.evaluate(()=>__test.UI.open);
  const iid=await p.evaluate(()=>__test.P().questions.at(-1).items[0].id);
  const field=p.locator(`[data-r="it.${qid}.${iid}.text"]`);
  await p.evaluate(()=>{const q=__test.P().questions.at(-1);q.items[0].choices=['خيار أول','خيار ثان'];__test.commit();});
  await field.fill('قبل هنا بعد');
  await field.evaluate(el=>{const s=getSelection(),r=document.createRange();r.setStart(el.firstChild,4);r.setEnd(el.firstChild,7);s.removeAllRanges();s.addRange(r);el.focus();});
  await p.locator('.ribbon [data-act=rEq]').click();
  await p.locator('[data-act=eqAdd][data-t=root]').click();
  await p.locator('[data-act=eqRoot][data-v="3"]').click();
  await p.locator('[data-eq=x]').fill('٨');
  await p.locator('[data-act=eqOk]').click();
  let text=await p.evaluate(()=>__test.P().questions.at(-1).items[0].text);
  ok('inline equation replaces selection and retains both sides',text.includes('قبل')&&text.includes('بعد')&&!text.includes('هنا')&&text.includes('\\sqrt[٣]{٨}'));
  await field.locator('.eqc').click();
  await p.locator('[data-act=eqRoot][data-v="4"]').click();
  await p.locator('[data-eq=x]').fill('١٦');
  await p.locator('[data-act=eqOk]').click();
  text=await p.evaluate(()=>__test.P().questions.at(-1).items[0].text);
  ok('existing root can be edited without losing prose',text.includes('\\sqrt[٤]{١٦}')&&text.includes('قبل')&&text.includes('بعد'));
  await p.locator(`[data-lay="${qid}"] summary`).click();
  await p.locator(`[data-path="q.${qid}.chLayout"][data-v=line]`).click();
  ok('layout section remains expanded after changing choices',await p.locator(`[data-lay="${qid}"]`).getAttribute('open')!==null);
  ok('separate choice line renders',await p.locator(`#pages [data-q="${qid}"] .chl`).count()===1);
  await p.locator(`[data-act=more][data-i="${iid}"]`).click();
  await p.locator('[data-act=tbAdd]').click();
  await p.locator(`[data-r="it.${qid}.${iid}.cell.1.1"]`).fill('اختبار');
  await p.locator('[data-act=tbRow][data-d="1"]').click();
  ok('table row and cell edits are retained',await p.evaluate(()=>{const t=__test.P().questions.at(-1).items[0].table;return t.rows.length===4&&t.rows[1][1]==='اختبار';}));
  await p.locator('[data-act=undo]').click();
  ok('table row addition can be undone',await p.evaluate(()=>__test.P().questions.at(-1).items[0].table.rows.length===3));
  await p.locator('[data-act=redo]').click();
  ok('table row addition can be redone',await p.evaluate(()=>__test.P().questions.at(-1).items[0].table.rows.length===4));
  await p.locator('details.menu summary').click();await p.locator('[data-act=wizard]').click();
  await p.locator('[data-act=wz][data-f=stage][data-v=intermediate]').click();
  await p.locator('[data-act=wzNext]').click();await p.locator('[data-act=wzNext]').click();await p.locator('[data-act=wzNext]').click();
  await p.evaluate(()=>{__test.P().questions[0].prompt='عمل المتوسطة محفوظ';__test.P().pristine=false;__test.commit();});
  await p.locator('details.menu summary').click();await p.locator('[data-act=wizard]').click();
  await p.locator('[data-act=wz][data-f=stage][data-v=primary]').click();
  await p.locator('[data-act=wzNext]').click();await p.locator('[data-act=wzNext]').click();
  ok('replacement checkbox is initially off when switching stages',!await p.locator('[data-wz=replace]').isChecked());
  await p.locator('[data-act=wzNext]').click();
  ok('switching stages retains work in both stages',await p.evaluate(()=>__test.S.stages.intermediate.questions[0].prompt==='عمل المتوسطة محفوظ'&&__test.P().questions.at(-1).items[0].text.includes('قبل')));
  await p.locator('details.menu summary').click();
  const down=p.waitForEvent('download');await p.locator('.menu-m [data-act=save]').click();
  const d=await down,loc=await d.path(),data=JSON.parse(fs.readFileSync(loc));
  ok('download includes all three stage exams',data.version===13&&Object.keys(data.stages).length===3&&data.stages.intermediate.questions[0].prompt==='عمل المتوسطة محفوظ');
  fs.writeFileSync(path.join(root,'tests','saved-test.json'),JSON.stringify(data));
  await p.locator('#fileIn').setInputFiles(path.join(root,'tests','saved-test.json'));
  ok('all-stage file import retains edited table',await p.evaluate(()=>__test.P().questions.at(-1).items[0].table.rows.length===4));
  const math=await p.evaluate(()=>{const t=__test;return{malformed:t.parsePieces('\\sqrt['),nested:t.piecesToTex(t.parsePieces('\\left(\\frac{1}{2}\\right)^2')),root:t.texProblem('\\sqrt[3]{8}'),bad:t.texProblem('\\frac{1}{'),unit:t.texToHTML('\\qty{9.8}{m/s^{2}}','en'),closed:t.texToHTML('[x]','en')};});
  ok('malformed root does not hang',math.malformed.length===1);
  ok('nested power survives editor round trip',math.nested==='\\left(\\frac{1}{2}\\right)^2');
  ok('unbalanced equations are identified',math.bad&&!math.root);
  ok('unit letters are upright',!math.unit.includes('<i>'));
  ok('closing square bracket is not lost',math.closed.includes(']'));
  for(const width of [360,390,768,1280]){
   await p.setViewportSize({width,height:900});
   await p.evaluate(()=>{__test.UI.view=innerWidth<1024?'preview':'questions';document.querySelector('#app').dataset.view=__test.UI.view;document.activeElement.blur();__test.renderPaper();});
   await p.waitForTimeout(200);
   const metrics=await p.evaluate(()=>({width:innerWidth,body:document.body.scrollWidth,pages:document.querySelectorAll('.page').length,tooTall:document.querySelectorAll('.too-tall').length,tooWide:document.querySelectorAll('.too-wide').length,font:document.querySelector('#pages').style.getPropertyValue('--fs')}));
   report.viewports.push(metrics);ok(`no body overflow at ${width}px`,metrics.body<=width);
   ok(`font remains at least 13pt at ${width}px`,parseFloat(metrics.font)>=13);
   ok(`normal exam is not falsely marked oversized at ${width}px`,metrics.tooTall===0&&metrics.tooWide===0);
  }
  await p.screenshot({path:path.join(root,'tests','desktop.png')});
  await p.evaluate(()=>{const p=__test.P();p.questions=Array.from({length:18},()=>__test.kindTemplate('branches',false));p.fit=false;__test.commit();});
  await p.waitForTimeout(200);
  const multi=await p.evaluate(()=>({pages:document.querySelectorAll('.page').length,headers:document.querySelectorAll('.ph').length,footers:document.querySelectorAll('.pf').length,flips:document.querySelectorAll('.pflip').length,lastHasFooter:!!document.querySelector('.page:last-child .pf')}));
  ok('multipage: header on first only and footer on last only',multi.pages>1&&multi.headers===1&&multi.footers===1&&multi.lastHasFooter&&multi.flips===multi.pages-1);
  await p.pdf({path:path.join(root,'tests','exam.pdf'),format:'A4',preferCSSPageSize:true,printBackground:true,displayHeaderFooter:false});
  ok('PDF was generated',fs.statSync(path.join(root,'tests','exam.pdf')).size>1000);
  ok('no uncaught browser errors',report.errors.length===0);
 }catch(e){report.failure=e.stack;throw e;}
 finally{fs.writeFileSync(path.join(root,'tests','browser-results.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report,null,2));}
})();
