import assert from 'node:assert/strict';
import fs from 'node:fs';
import typescript from 'typescript';
const src=fs.readFileSync(new URL('../src/curriculum.ts',import.meta.url),'utf8');
const js=typescript.transpileModule(src,{compilerOptions:{module:typescript.ModuleKind.ESNext,target:typescript.ScriptTarget.ES2022}}).outputText;
const {GRADES,subjectsFor,numberingFor,examTitle,digitsFor,partLabel}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
assert.deepEqual(subjectsFor('primary',GRADES.primary[0]),['اللغة العربية','الرياضيات']);
assert.equal(subjectsFor('primary',GRADES.primary[1]).length,6);
assert.equal(numberingFor('primary','الرياضيات'),'arabic');
assert.equal(numberingFor('primary','اللغة الإنكليزية'),'latin');
assert.equal(numberingFor('intermediate','الرياضيات'),'latin');
assert.equal(numberingFor('intermediate','الاجتماعيات'),'arabic');
assert.equal(numberingFor('preparatory','الاقتصاد'),'arabic');
assert.equal(numberingFor('preparatory','الفيزياء'),'latin');
assert.ok(subjectsFor('preparatory','السادس الأدبي').includes('الاقتصاد'));
assert.ok(!subjectsFor('preparatory','السادس العلمي').includes('الاقتصاد'));
assert.equal(examTitle('نصف السنة'),'أسئلة امتحانات نصف السنة');
assert.equal(digitsFor('2027-2026','arabic'),'٢٠٢٧-٢٠٢٦');
assert.equal(digitsFor('٢٠٢٧-٢٠٢٦','latin'),'2027-2026');
assert.equal(partLabel(0,'arabic'),'أ');
assert.equal(partLabel(1,'latin'),'B');
console.log('Curriculum, grade/subject selectors, RTL/LTR numbering passed.');
