const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),report={checks:[],errors:[]};
const ok=(n,v)=>{assert(v,n);report.checks.push(n);};
(async()=>{
 const local='/ms-playwright/chromium_headless_shell-1208/chrome-headless-shell-linux64/chrome-headless-shell';
 const b=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||(fs.existsSync(local)?local:undefined),args:['--no-sandbox']});
 try{
  const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true});p.setDefaultTimeout(10000);
  p.on('pageerror',e=>report.errors.push(e.stack));
  let html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace('loadFont();renderAll();pushHist();',"window.__test={S,P,UI,commit,renderPaper,makeProject,normProject,kindTemplate,setPath,loadFont,doPrint,onFont};loadFont();renderAll();pushHist();");
  await p.route('**/*',r=>r.request().url().startsWith('file:')?r.fulfill({contentType:'text/html',body:html}):r.abort());
  await p.goto('file://'+path.join(root,'index.html'),{waitUntil:'commit'});
  await p.locator('[data-act=homeNew]').tap();
  for(let i=0;i<3;i++)await p.locator('#wizard [data-act=wzNext]').click();
  await p.evaluate(()=>{__test.UI.view='questions';__test.UI.adding=false;__test.commit();});
  await p.locator('[data-act=adding]').click();await p.locator('[data-act=addQ][data-kind=branches]').click();
  const ids=await p.evaluate(()=>{const q=__test.P().questions.at(-1);return{q:q.id,x:q.items[0].id};}),base=`it.${ids.q}.${ids.x}`;
  const field=p.locator(`[data-r="${base}.text"]`);
  await field.fill('مرحبا عالم');
  await field.evaluate(el=>{el.focus();const r=document.createRange();r.setStart(el.firstChild,5);r.collapse(true);getSelection().removeAllRanges();getSelection().addRange(r);});
  await p.locator('.ribbon [data-act=rEq]').tap();
  await p.locator('[data-act=eqAdd][data-t=frac]').tap();
  await p.locator('[data-eq=a]').fill('12');await p.locator('[data-eq=b]').fill('3');
  await p.locator('[data-eq=b]').evaluate(el=>{el.focus();el.setSelectionRange(1,1);});
  await p.locator('[data-act=eqTab][data-k=أساسية]').tap();
  await p.locator('[data-sym="+"]').tap();
  ok('touch symbol inserts into denominator after changing tab',await p.locator('[data-eq=b]').inputValue()==='3+');
  await p.locator('[data-eq=b]').fill('3');
  await p.locator('[data-act=eqOk]').tap();
  ok('touch equation remains inline',await field.locator('.eqc').count()===1);
  await p.locator(`[data-act=more][data-i="${ids.x}"]`).tap();
  await p.locator(`[data-path="${base}.align"][data-v=center]`).tap();
  await p.locator(`[data-path="${base}.answerLines"][data-v="4"]`).tap();
  ok('answer space contains four lines',await p.locator(`#pages [data-q="${ids.q}"] .answer-lines>div`).count()===4);
  ok('branch alignment is saved',await p.evaluate(()=>__test.P().questions.at(-1).items[0].align==='center'));
  await p.locator('[data-act=tbAdd]').tap();
  await p.locator(`[data-r="${base}.cell.1.1"]`).fill('محتوى يبقى');
  await p.locator('.table-edit-more summary').tap();
  await p.locator(`[data-r="${base}.cell.1.1"]`).tap();
  await p.locator('[data-act=tbEdit][data-op=rowBefore]').tap();
  ok('row inserted before selected cell without losing data',await p.evaluate(()=>{const r=__test.P().questions.at(-1).items[0].table.rows;return r.length===4&&r[2][1]==='محتوى يبقى';}));
  await p.locator('.table-edit-more summary').tap();
  await p.locator(`[data-r="${base}.cell.2.1"]`).tap();
  await p.locator('[data-act=tbEdit][data-op=colBefore]').tap();
  ok('column inserted before selected cell without losing data',await p.evaluate(()=>{const r=__test.P().questions.at(-1).items[0].table.rows;return r[0].length===4&&r[2][2]==='محتوى يبقى';}));
  await p.locator('.table-edit-more summary').tap();await p.locator(`[data-r="${base}.cell.2.2"]`).tap();
  await p.locator('[data-act=tbEdit][data-op=delRow]').tap();
  ok('selected row can be deleted',await p.evaluate(()=>__test.P().questions.at(-1).items[0].table.rows.length===3));
  await p.locator('[data-act=undo]').tap();
  ok('selected row deletion is undoable',await p.evaluate(()=>__test.P().questions.at(-1).items[0].table.rows[2][2]==='محتوى يبقى'));
  await p.locator(`[data-act=toggle][data-q="${ids.q}"]`).tap();
  await p.evaluate(()=>{const t=__test;const q=t.P().questions.at(-1);q.items[0].text='$\\sqrt[$';t.commit();window.printCalls=0;window.print=()=>printCalls++;});
  await p.locator('.top [data-act=print]').tap();
  await p.waitForTimeout(200);
  ok('malformed imported equation blocks PDF',await p.evaluate(()=>printCalls===0)&&await p.locator('#toast').textContent().then(x=>x.includes('معادلة غير مكتملة')));
  await p.evaluate(()=>{const t=__test,p=t.P();p.questions=[t.kindTemplate('branches',false)];p.questions[0].items[0].text='أجب عن السؤال';p.questions[0].items[0].answerLines=4;t.commit();});
  await p.locator('.top [data-act=print]').tap();await p.waitForTimeout(200);
  ok('valid exam reaches print',await p.evaluate(()=>printCalls===1));
  // Race two custom fonts; only the final font should survive.
  const a=fs.readFileSync(path.join(root,'fonts/times.woff2')).toString('base64'),c=fs.readFileSync(path.join(root,'fonts/amiri.woff2')).toString('base64');
  await p.evaluate(async ({a,c})=>{const t=__test;t.P().customFont={src:'data:font/woff2;base64,'+a,name:'A'};const r1=t.loadFont();t.P().customFont={src:'data:font/woff2;base64,'+c,name:'B'};const r2=t.loadFont();await Promise.all([r1,r2]);},{a,c});
  ok('custom font race leaves one current face',await p.evaluate(()=>[...document.fonts].filter(x=>x.family==='ExamUserFont').length===1));
  await p.evaluate(async()=>{__test.P().customFont=null;await __test.loadFont();});
  ok('leaving custom font removes obsolete face',await p.evaluate(()=>![...document.fonts].some(x=>x.family==='ExamUserFont')));
  await p.evaluate(async a=>{const bytes=Uint8Array.from(atob(a),c=>c.charCodeAt(0));const original=__test.S.active,other=original==='primary'?'intermediate':'primary';__test.onFont(new File([bytes],'stage-font.woff2',{type:'font/woff2'}));__test.S.active=other;await new Promise(r=>setTimeout(r,200));window.stageFontCorrect=__test.S.stages[original].customFont?.name==='stage-font'&&!__test.S.stages[other].customFont;__test.S.active=original;__test.P().customFont=null;__test.P().font='sans';await __test.loadFont();},a);
  ok('font upload stays with originating stage when switching during read',await p.evaluate(()=>stageFontCorrect));
  await p.evaluate(()=>{const t=__test,p=t.P(),q=p.questions[0];p.meta.logo='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jVZkAAAAASUVORK5CYII=';q.items[0].image={src:p.meta.logo,w:10,r:1,align:'center',side:false};t.commit();});
  await p.waitForTimeout(400);
  ok('image and logo load without breaking layout',await p.locator('#pages .qi img').count()===1&&await p.locator('#pages .lg img').count()===1&&await p.locator('#pages .too-wide,#pages .too-tall').count()===0);
  const pos=()=>[...document.querySelectorAll('.page')].map(pg=>{const b=pg.getBoundingClientRect();return{n:pg.querySelectorAll('.qb').length,w:b.width,h:b.height,items:[...pg.querySelectorAll('.qb')].map(q=>{const r=q.getBoundingClientRect();return[(r.x-b.x)/b.width,(r.y-b.y)/b.height,r.width/b.width,r.height/b.height];})};});
  const before=await p.evaluate(pos);await p.emulateMedia({media:'print'});const after=await p.evaluate(pos);
  ok('preview and print have same blocks and proportional positions',before.length===after.length&&before.every((pg,i)=>pg.n===after[i].n&&pg.items.every((r,j)=>r.every((v,k)=>Math.abs(v-after[i].items[j][k])<0.005))));
  await p.emulateMedia({media:'screen'});
  await p.reload({waitUntil:'commit'});await p.waitForTimeout(200);await p.locator('[data-act=continueProject]').click();
  ok('saved exam restores after reload',await p.evaluate(()=>__test.P().questions[0].items[0].answerLines===4));
  await p.evaluate(()=>{const t=__test,p=t.P(),q=p.questions[0];q.items[0].table={head:true,full:true,align:'left',rows:[['A','B'],['C','D']]};t.UI.view='questions';t.UI.open=q.id;t.UI.more[q.items[0].id]=true;t.commit();});
  const pastePath=await p.evaluate(()=>{const q=__test.P().questions[0];return`it.${q.id}.${q.items[0].id}`;});
  await p.locator(`[data-r="${pastePath}.cell.1.0"]`).evaluate(el=>{el.focus();const d=new DataTransfer();d.setData('text/plain','أ\tب\nج\tد');el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}));});
  ok('tab-separated clipboard populates rows and columns',await p.evaluate(()=>{const r=__test.P().questions[0].items[0].table.rows;return r.length===3&&r[1][0]==='أ'&&r[1][1]==='ب'&&r[2][0]==='ج'&&r[2][1]==='د';}));
  await p.locator('[data-act=undo]').tap();
  ok('table clipboard paste is one undoable change',await p.evaluate(()=>{const r=__test.P().questions[0].items[0].table.rows;return r.length===2&&r[1][0]==='C';}));
  await p.evaluate(()=>{const q=__test.P().questions[0];__test.UI.open=q.id;__test.commit();});
  const textPath=p.locator(`[data-r="${pastePath}.text"]`);
  await textPath.evaluate(el=>{el.focus();const r=document.createRange();r.selectNodeContents(el);getSelection().removeAllRanges();getSelection().addRange(r);const d=new DataTransfer();d.setData('text/plain','السطر الأول\nالسطر الثاني');el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}));});
  ok('multiline prose paste retains line breaks',await p.evaluate(()=>__test.P().questions[0].items[0].text.includes('السطر الأول\nالسطر الثاني')));
  await p.evaluate(()=>{const p=__test.P();p.meta.title='عنوان يدوي خاص';p.meta.titleAuto=false;p.meta.subtitle='صف خاص';p.meta.subtitleAuto=false;p.meta.show.year=false;p.theme='teal';p.font='times';p.size=15;__test.commit();});
  await p.locator('.nav [data-v=paper]').tap();
  await p.locator('.sec').last().locator('summary').tap();await p.locator('#sideBody [data-act=new]').tap();
  ok('blank sheet preserves custom header and design preferences',await p.evaluate(()=>{const p=__test.P();return !p.questions.length&&p.meta.title==='عنوان يدوي خاص'&&p.meta.subtitle==='صف خاص'&&p.meta.show.year===false&&p.theme==='teal'&&p.font==='times'&&p.size===15;}));
  await p.locator('[data-act=undo]').tap();
  ok('blank-sheet operation is undoable',await p.evaluate(()=>__test.P().questions.length===1));
  const long='نص طويل محفوظ '.repeat(600);
  await p.evaluate(long=>{const p=__test.P();p.questions[0].items[0].text=long;p.questions[0].prompt=long;p.questions[0].items[0].table.rows[0][0]=long;__test.commit();},long);
  await p.waitForTimeout(600);await p.reload({waitUntil:'commit'});await p.waitForFunction(()=>!!window.__test);await p.locator('[data-act=continueProject]').click();
  ok('long branch, prompt and table cell survive reload without truncation',await p.evaluate(long=>{const q=__test.P().questions[0];return q.prompt===long&&q.items[0].text===long&&q.items[0].table.rows[0][0]===long;},long));
  await p.evaluate(()=>{const p=__test.P();p.questions[0].prompt='نسخة سليمة';__test.commit();});await p.waitForTimeout(600);
  await p.addInitScript(()=>localStorage.setItem('almufeed-exam-v13','{broken json'));
  await p.reload({waitUntil:'commit'});await p.waitForFunction(()=>!!window.__test);await p.waitForTimeout(100);
  ok('damaged local save falls back to valid backup',await p.evaluate(()=>__test.P().questions.length===1&&__test.P().meta.title==='عنوان يدوي خاص'));
  ok('backup recovery tells user to export',await p.locator('#toast').textContent().then(t=>t.includes('استُعيدت')));
  ok('no uncaught errors during touch interactions',report.errors.length===0);
 }catch(e){report.failure=e.stack;throw e;}finally{fs.writeFileSync(path.join(root,'tests/extended-results.json'),JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify(report,null,2));}
})();
