const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('assert'),{execFileSync}=require('child_process');
const root=path.resolve(__dirname,'..');
(async()=>{
 const executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||(fs.existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined);
 const browser=await chromium.launch({...(executablePath?{executablePath}:{}),args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,acceptDownloads:true});
 const page=await context.newPage();page.setDefaultTimeout(10000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const log=[],ok=(name,value)=>{assert(value,name);log.push(name)};
 try {
  await page.evaluate(()=>{const values={};Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>values[k]??null,setItem:(k,v)=>{values[k]=String(v)},removeItem:k=>{delete values[k]}}})});
  let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
  html=html.replace('loadFont();renderAll();pushHist();','window.__test={S,P,UI,commit,renderPaper,kindTemplate,makeProject};loadFont();renderAll();pushHist();');
  await page.setContent(html,{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);
  await page.screenshot({path:path.join(root,'tests','v14-home-mobile.png')});
  ok('mobile welcome shows the 3-stage journey',await page.locator('.home-flow span').count()===3);
  await page.locator('[data-act=homeNew]').click();
  for(let i=0;i<3;i++)await page.locator('#wizard [data-act=wzNext]').click();
  ok('mobile navigation has three destinations',await page.locator('.nav [data-act=view]').count()===3);
  ok('editor highlights six common question types',await page.locator('.question-picker>.addsheet [data-act=addQ]').count()===6);
  ok('other question types are available under disclosure',await page.locator('.picker-more [data-act=addQ]').count()>0);
  await page.waitForTimeout(420);await page.locator('#toast').evaluate(el=>el.hidden=true);
  await page.screenshot({path:path.join(root,'tests','v14-editor-mobile.png')});
  console.log('MOBILE_LAYOUT_DIAGNOSTIC',JSON.stringify(await page.evaluate(()=>{
    const pick=document.querySelector('.question-picker [data-kind=branches]');
    const names=['.app','.ribbon','.main','.side','.sbody','.question-picker','.nav'];
    const geom=Object.fromEntries(names.map(key=>{const e=document.querySelector(key),b=e?.getBoundingClientRect(),cs=e&&getComputedStyle(e);return [key,{top:b?.top,bottom:b?.bottom,height:b?.height,position:cs?.position,gridRows:cs?.gridTemplateRows,overflow:cs?.overflowY,scrollHeight:e?.scrollHeight,clientHeight:e?.clientHeight}]}));
    const b=pick.getBoundingClientRect();
    return {viewport:{width:innerWidth,height:innerHeight},geom,picker:{top:b.top,bottom:b.bottom,hit:document.elementFromPoint(b.left+b.width/2,b.top+b.height/2)?.closest('.nav')?'NAV':'BUTTON'},cssNavigationTrack:[...document.styleSheets].some(sheet=>{try{return [...sheet.cssRules].some(x=>x.cssText.includes('Mobile navigation occupies'))}catch{return false}})};
  })));
  await page.locator('.question-picker [data-kind=branches]').click();
  const qid=await page.evaluate(()=>__test.P().questions.at(-1).id);
  await page.locator(`[data-r="q.${qid}.prompt"]`).fill('أجب عن السؤال الآتي:');
  await page.locator(`[data-b="q.${qid}.score"]`).fill('20');
  await page.waitForTimeout(650);
  ok('question count is computed from the document',await page.locator('.exam-statline').textContent().then(t=>t.includes('1')||t.includes('١')));
  ok('marks total updates from question score',await page.locator('.exam-statline').textContent().then(t=>t.includes('٢٠')||t.includes('20')));
  await page.locator('.nav [data-v=paper]').click();
  ok('setup shows appearance as a contextual action',await page.locator('.setup-appearance').isVisible());
  await page.locator('.setup-appearance [data-v=style]').click();
  ok('appearance retains existing typography and palette tools',await page.locator('.pad-style .themes').isVisible());
  await page.locator('.pad-style [data-v=paper]').first().click();
  await page.locator('.nav [data-v=preview]').click();
  ok('preview displays A4',await page.locator('.canvas .page').count()>=1);
  await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(250);
  await page.screenshot({path:path.join(root,'tests','v14-preview-mobile.png')});
  const pdfPath=path.join(root,'tests','v14-exam.pdf');
  const printPages=await page.locator('#pages .page').count();
  await page.pdf({path:pdfPath,format:'A4',preferCSSPageSize:true,printBackground:true,displayHeaderFooter:false});
  ok('PDF export generates non-empty document',fs.statSync(pdfPath).size>1000);
  const pageCount=file=>Number(execFileSync('pdfinfo',[file],{encoding:'utf8'}).match(/^Pages:\s+(\d+)/m)?.[1]||0);
  ok('single-page A4 PDF matches preview without a blank page',printPages===1&&pageCount(pdfPath)===printPages);
  await page.setViewportSize({width:1280,height:900});
  await page.locator('.workflow [data-v=questions]').click();
  ok('desktop renders the guided workflow once',await page.locator('.workflow button').count()===3);
  ok('desktop avoids double side tabs',await page.locator('.stabs').isHidden());
  await page.screenshot({path:path.join(root,'tests','v14-editor-desktop.png')});
  await page.locator('.workflow [data-v=preview]').click();
  ok('desktop print preview hides the input sidebar',await page.locator('.side').isHidden());
  await page.screenshot({path:path.join(root,'tests','v14-preview-desktop.png')});
  await page.evaluate(()=>{const p=__test.P();p.questions=Array.from({length:18},()=>__test.kindTemplate('branches',false));p.fit=false;__test.commit();});
  await page.waitForTimeout(500);
  const multi=await page.evaluate(()=>({pages:document.querySelectorAll('#pages .page').length,headers:document.querySelectorAll('#pages .ph').length,footers:document.querySelectorAll('#pages .pf').length,flips:document.querySelectorAll('#pages .pflip').length,overflow:document.querySelectorAll('#pages .too-tall,#pages .too-wide').length}));
  ok('long exams paginate to multiple A4 sheets',multi.pages>1);
  ok('multipage exams display one header and one footer',multi.headers===1&&multi.footers===1&&multi.flips===multi.pages-1);
  ok('normal long exam has no clipped blocks',multi.overflow===0);
  const longPDF=path.join(root,'tests','v14-multipage.pdf');await page.pdf({path:longPDF,preferCSSPageSize:true,printBackground:true,displayHeaderFooter:false});
  ok('long PDF page count matches the exact A4 preview',pageCount(longPDF)===multi.pages);
  for(const width of [360,390,768,1280]){await page.setViewportSize({width,height:900});ok('no horizontal document overflow at '+width,await page.evaluate(()=>document.body.scrollWidth<=innerWidth));}
  ok('no browser exceptions',errors.length===0);
  fs.writeFileSync(path.join(root,'tests','v14-ux-results.json'),JSON.stringify({passed:log.length,checks:log,errors},null,2));
  console.log(JSON.stringify({passed:log.length,checks:log,errors},null,2));
 }catch(err){console.error('SMOKE FAILED',err.stack,'PAGE ERRORS',errors);throw err}finally{await browser.close()}
})();
